### ISSUE TITLE
bug: No newline between each command for "Export Hotkeys" in Windows

### ISSUE THREAD

**Issue by ajitzero** [joethei/obsidian-key-promoter#13]
As in title.

**Screenshot:**

![image](https://github.com/joethei/obsidian-key-promoter/assets/19947758/d8588a49-b6e7-4ebf-9b6c-c4a9d994201a)

**Comment by claremacrae** [comment]
The manual fix for this is to go to the plugin's settings and add a newline at the end of the template text.

**Comment by claremacrae** [comment]
You have to delete the first exported file though, as it refuses to overwrite an existing export.

**Comment by AlanEdd** [comment]
Oh yes, I was editing it in the main.js file. 🤦‍♀
Looks nice now to print! 
I have backticks to style the shortcuts.
"`{{hotkey}}` {{commandName}}\n"

![image](https://github.com/user-attachments/assets/80e3a559-af30-42d0-a4c6-86522e9bfcc7)
