### ISSUE TITLE
Custom hotkeys not listed, defaults used.

### ISSUE THREAD

**Issue by AlanEdd** [joethei/obsidian-key-promoter#15]
Hey there, apologies about not seeing the duplicate earlier. I have exported the hotkeys and initially it looked fine but I see lots of shortcuts are showing as the default rather than the hotkeys that I have changed them to.
e.g..
`Ctrl + ,    Open settings  ---app:open-settings`

but the actual assignment is :
![image](https://github.com/user-attachments/assets/8e01397d-62b0-4fa3-b717-56d0e8b3a4dc)

I presume it is supposed to print the current user settings. I disabled all plugins except for Key Promoter to check.

**Comment by 4Source** [comment]
I also have the problem that only the default hotkeys are used. Whether I change it to another hotkey, remove the hotkey, or add a hotkey that originally didn't have one
