### ISSUE TITLE
Feature Request: Print all Hotkeys to File

### ISSUE THREAD

**Issue by brimwats** [joethei/obsidian-key-promoter#4]
Same as https://github.com/pjeby/hotkey-helper/issues/1 — I would like to print all the hotkeys to a file so I can make an anki deck. a different sort of promotion but thought i'd ask :) feel free to close if out of scope

**Comment by brimwats** [comment]
wow, that's neat! yeah that's really perfect!

**Comment by joethei** [comment]
hey @brimwats I just added the ability to export hotkeys to a file.
You can define a template in the settings which gets run for each hotkey.
For the Spaced Repetition plugin for example the template would be:
```
{{commandName}}::{{hotkey}}

```
You can select which hotkeys get exported with the settings for assigned/unassigned commands.
The hotkeys get exported to a file hotkeys-export.md in the root folder of your vault.
The command to export is `Key Promoter: Export Hotkeys`
